/**
 * GENERATED by `npm run measure`. Do not edit by hand.
 *
 * The Measured Distribution: what 16 rows of honest physics actually do.
 *
 * Raw per-bin counts over seeds 0..99,999,999. Counts rather than
 * probabilities, because counts are exact and let a later run be merged in.
 *
 * See src/sim/measured.ts for the derived views, and ADR 0001 for why the
 * Derived Table is solved against these numbers instead of against a binomial.
 */

/** The tuning these counts were measured under; see src/sim/fingerprint.ts. */
export const MEASURED_TUNING = "9c96323e";

export const MEASURED_SAMPLES = 100000000;

/**
 * Drops that hit the step guard, and are therefore absent from the counts
 * above. The probabilities divide by MEASURED_SAMPLES - MEASURED_UNSETTLED, so
 * a handful does not bias the distribution — but each one is a round that would
 * hang in a real game, so they are named rather than merely counted.
 */
export const MEASURED_UNSETTLED = 3;

/** Every seed above that never settled, replayable one by one. */
export const UNSETTLED_SEEDS: readonly number[] = [
  59027096,
  59068407,
  83811353,
];

/** Simulated seconds from spawn to settle, averaged over every drop. */
export const MEASURED_MEAN_FALL_SECONDS = 4.0353;

export const MEASURED_COUNTS: readonly number[] = [
  700,
  33182,
  225212,
  858891,
  2775043,
  6676323,
  12290583,
  17387197,
  19517211,
  17367367,
  12286864,
  6686089,
  2775492,
  859845,
  225497,
  33747,
  754,
];

/**
 * Seeds 0..19999, the same drops as the first slice of the run
 * above. Cheap enough for measured.test.ts to reproduce exactly, which is what
 * proves this artefact came out of the solver in the tree rather than out of an
 * older one that happened to leave a plausible-looking file behind.
 */
export const SPOT_CHECK_SAMPLES = 20000;

export const SPOT_CHECK_COUNTS: readonly number[] = [
  1,
  5,
  46,
  200,
  512,
  1319,
  2496,
  3456,
  3933,
  3538,
  2379,
  1305,
  579,
  179,
  47,
  5,
  0,
];
